import {
  AdminPartner,
  AdminTicket,
  CustomerPenaltyItem,
  FraudAuditLog,
  GlobalPlatformSettings,
  LiveMapPin,
  PendingCommissionItem,
  ServicePricingItem,
  SOSAlert,
} from './types';

export const INITIAL_SOS_ALERTS: SOSAlert[] = [
  {
    id: 'sos-001',
    orderId: '#8922',
    triggeredBy: 'Partner (Rahul)',
    partnerName: 'Rahul Sharma',
    partnerPhone: '+91 98765 43210',
    customerName: 'Amit Verma',
    customerPhone: '+91 91234 56780',
    location: 'KGMU Hospital Trauma Center, Gate 2',
    coordinates: '26.8692° N, 80.9168° E',
    timestamp: '2 mins ago (11:07 AM)',
    status: 'ACTIVE',
    batteryLevel: '68%',
    taskTitle: 'Emergency OPD Token & Patient Wheelchair support',
    notes: 'Partner pressed hardware red SOS button. Audio recording streaming to Safety Desk.',
  },
  {
    id: 'sos-002',
    orderId: '#8915',
    triggeredBy: 'Customer (Priya)',
    partnerName: 'Deepak Yadav',
    partnerPhone: '+91 98234 11223',
    customerName: 'Priya Saxena',
    customerPhone: '+91 94551 09876',
    location: 'Hazratganj Metro Station, Exit 3',
    coordinates: '26.8524° N, 80.9431° E',
    timestamp: '42 mins ago',
    status: 'RESOLVED',
    batteryLevel: '82%',
    taskTitle: 'Elderly Assistance with Medicine Bag',
    notes: 'False alarm triggered accidentally while phone in purse. Verified by agent call.',
  },
];

export const INITIAL_MAP_PINS: LiveMapPin[] = [
  {
    id: 'pin-1',
    partnerName: 'Rahul S.',
    phone: '+91 98765 43210',
    status: 'En Route',
    orderId: '#8922',
    customerName: 'Amit Verma',
    serviceName: 'Hospital Assistance',
    xPercent: 44,
    yPercent: 38,
    battery: 68,
    speedKmh: 18,
    address: 'KGMU Hospital Road, Chowk',
  },
  {
    id: 'pin-2',
    partnerName: 'Vikram Patel',
    phone: '+91 98112 34567',
    status: 'Available',
    xPercent: 28,
    yPercent: 52,
    battery: 92,
    speedKmh: 0,
    address: 'Charbagh Railway Station Circle',
  },
  {
    id: 'pin-3',
    partnerName: 'Sunita Devi',
    phone: '+91 97654 32109',
    status: 'At Work',
    orderId: '#8919',
    customerName: 'Dr. Alok Sen',
    serviceName: 'Queue (Line) Waiter',
    xPercent: 62,
    yPercent: 32,
    battery: 79,
    speedKmh: 2,
    address: 'Passport Seva Kendra, Gomti Nagar',
  },
  {
    id: 'pin-4',
    partnerName: 'Deepak Yadav',
    phone: '+91 98234 11223',
    status: 'Available',
    xPercent: 74,
    yPercent: 64,
    battery: 84,
    speedKmh: 0,
    address: 'Patrakarpuram Market, Gomti Nagar',
  },
  {
    id: 'pin-5',
    partnerName: 'Rajesh Kumar',
    phone: '+91 99887 76655',
    status: 'En Route',
    orderId: '#8924',
    customerName: 'Meenakshi Iyer',
    serviceName: 'Shopping Assistance',
    xPercent: 50,
    yPercent: 70,
    battery: 45,
    speedKmh: 24,
    address: 'Alambagh Wholesale Market',
  },
  {
    id: 'pin-6',
    partnerName: 'Arun Trivedi',
    phone: '+91 94150 99881',
    status: 'Available',
    xPercent: 36,
    yPercent: 22,
    battery: 95,
    speedKmh: 0,
    address: 'Aminabad Book Bazaar Stand',
  },
];

export const INITIAL_TICKETS: AdminTicket[] = [
  {
    id: 'TCK-4081',
    orderId: '#8890',
    customerName: 'Suresh Chandra',
    partnerName: 'Vikram Patel',
    subject: 'Customer No-Show after 10-min wait at gate',
    status: 'WAITING FOR ADMIN',
    tag: 'Customer No-Show',
    priority: 'High',
    createdAt: '15 mins ago',
    messages: [
      {
        id: 'm1',
        sender: 'partner',
        senderName: 'Vikram Patel',
        text: 'Sir, I waited at B-14 Indira Nagar for 12 minutes. The customer is not picking phone calls. OTP not shared.',
        time: '11:02 AM',
      },
      {
        id: 'm2',
        sender: 'customer',
        senderName: 'Suresh Chandra',
        text: 'I was in an urgent doctor meeting. Please waive the ₹20 penalty.',
        time: '11:10 AM',
      },
    ],
  },
  {
    id: 'TCK-4078',
    orderId: '#8874',
    customerName: 'Ananya Roy',
    partnerName: 'Rajesh Kumar',
    subject: 'Wrong Cash Amount Collected (₹200 collected vs ₹160 app bill)',
    status: 'WAITING FOR ADMIN',
    tag: 'Wrong Cash Amount',
    priority: 'High',
    createdAt: '1 hour ago',
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        senderName: 'Ananya Roy',
        text: 'The partner claimed app was showing ₹200 and kept ₹40 extra. My order invoice says ₹160.',
        time: '10:14 AM',
      },
      {
        id: 'm2',
        sender: 'partner',
        senderName: 'Rajesh Kumar',
        text: 'Madam rounded up for 20 extra minutes of staircase luggage lifting as agreed verbal.',
        time: '10:20 AM',
      },
    ],
  },
  {
    id: 'TCK-4062',
    orderId: '#8850',
    customerName: 'Kunal Joshi',
    partnerName: 'Sunita Devi',
    subject: 'Task duration dispute on Govt Registry Queue',
    status: 'IN REVIEW',
    tag: 'Billing Dispute',
    priority: 'Medium',
    createdAt: '3 hours ago',
    messages: [
      {
        id: 'm1',
        sender: 'customer',
        senderName: 'Kunal Joshi',
        text: 'Sub-registrar counter was closed between 1 PM and 2 PM lunch break.',
        time: '08:45 AM',
      },
    ],
  },
];

export const INITIAL_PARTNERS: AdminPartner[] = [
  {
    id: 'PTR-1001',
    name: 'Mohd. Farhan',
    mobile: '+91 98877 66554',
    status: 'Pending',
    rating: 0,
    totalOrders: 0,
    joinedDate: 'Today, 09:30 AM',
    aadharNumber: 'XXXX-XXXX-4891',
    panNumber: 'BLRPF****M',
    assignedServices: [],
    city: 'Lucknow Central',
    kycSubmittedAt: '2026-09-20 09:32 AM',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PTR-1002',
    name: 'Pooja Singh',
    mobile: '+91 97766 55443',
    status: 'Pending',
    rating: 0,
    totalOrders: 0,
    joinedDate: 'Yesterday, 04:15 PM',
    aadharNumber: 'XXXX-XXXX-9124',
    panNumber: 'AKZPS****D',
    assignedServices: [],
    city: 'Gomti Nagar',
    kycSubmittedAt: '2026-09-19 04:18 PM',
    photoUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PTR-1003',
    name: 'Rahul Sharma',
    mobile: '+91 98765 43210',
    status: 'Active',
    rating: 4.88,
    totalOrders: 142,
    joinedDate: '12 Aug 2026',
    aadharNumber: 'XXXX-XXXX-1122',
    panNumber: 'ABCPS****K',
    assignedServices: ['hospital-assistance', 'shopping-assistance', 'queue-waiter'],
    city: 'Chowk, Lucknow',
    kycSubmittedAt: '2026-08-12 11:00 AM',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PTR-1004',
    name: 'Vikram Patel',
    mobile: '+91 98112 34567',
    status: 'Active',
    rating: 4.92,
    totalOrders: 289,
    joinedDate: '01 Jul 2026',
    aadharNumber: 'XXXX-XXXX-7788',
    panNumber: 'DKZPP****L',
    assignedServices: ['hospital-assistance', 'elderly-assistance', 'queue-waiter', 'document-assistance'],
    city: 'Indira Nagar',
    kycSubmittedAt: '2026-07-01 10:15 AM',
    photoUrl: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PTR-1005',
    name: 'Sunita Devi',
    mobile: '+91 97654 32109',
    status: 'Active',
    rating: 4.75,
    totalOrders: 88,
    joinedDate: '24 Aug 2026',
    aadharNumber: 'XXXX-XXXX-3344',
    panNumber: 'BWMPD****R',
    assignedServices: ['elderly-assistance', 'home-assistance', 'shopping-assistance'],
    city: 'Aliganj',
    kycSubmittedAt: '2026-08-24 02:40 PM',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'PTR-1006',
    name: 'Dinesh Yadav',
    mobile: '+91 99112 23344',
    status: 'Locked',
    rating: 3.4,
    totalOrders: 23,
    joinedDate: '05 Sep 2026',
    aadharNumber: 'XXXX-XXXX-9900',
    panNumber: 'GHJY****T',
    assignedServices: ['move-shift-help', 'skilled-help'],
    city: 'Alambagh',
    kycSubmittedAt: '2026-09-05 12:20 PM',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_SERVICES_PRICING: ServicePricingItem[] = [
  {
    id: 'hospital-assistance',
    nameEn: 'Hospital Assistance',
    nameHi: 'अस्पताल सहायता',
    baseRate: 2.0,
    minDurationMins: 30,
    minAmount: 60,
    isEnabled: true,
    category: 'Healthcare & Mobility',
    description: 'OPD queue token, patient wheeling, medicine & diagnostic reports collection',
  },
  {
    id: 'shopping-assistance',
    nameEn: 'Shopping Assistance',
    nameHi: 'खरीदारी सहायता',
    baseRate: 2.0,
    minDurationMins: 30,
    minAmount: 60,
    isEnabled: true,
    category: 'Daily Errands',
    description: 'Local bazaar runs, heavy bag carrying & bulk item transport from mandis',
  },
  {
    id: 'document-assistance',
    nameEn: 'Document Assistance',
    nameHi: 'दस्तावेज सहायता',
    baseRate: 2.0,
    minDurationMins: 30,
    minAmount: 60,
    isEnabled: true,
    category: 'Government & Legal',
    description: 'Govt office paperwork, notary runs, Xerox & stamp vendor queues',
  },
  {
    id: 'elderly-assistance',
    nameEn: 'Elderly Assistance',
    nameHi: 'बुजुर्ग सहायता',
    baseRate: 2.5,
    minDurationMins: 30,
    minAmount: 75,
    isEnabled: true,
    category: 'Care & Escort',
    description: 'Doctor clinic visits, bank errands, park walks & companionship support',
  },
  {
    id: 'pet-assistance',
    nameEn: 'Pet Assistance',
    nameHi: 'पालतू पशु सहायता',
    baseRate: 2.5,
    minDurationMins: 30,
    minAmount: 75,
    isEnabled: true,
    category: 'Pet Care',
    description: 'Dog walking (30-60 mins), vet clinic escort, pet food & supplies pickup',
  },
  {
    id: 'home-assistance',
    nameEn: 'Home Assistance',
    nameHi: 'गृह सहायता',
    baseRate: 3.0,
    minDurationMins: 30,
    minAmount: 90,
    isEnabled: true,
    category: 'Home & Living',
    description: 'Furniture rearrangement inside home, terrace cleaning & garden chores',
  },
  {
    id: 'move-shift-help',
    nameEn: 'Move & Shift Help',
    nameHi: 'सामान शिफ्टिंग मदद',
    baseRate: 3.0,
    minDurationMins: 30,
    minAmount: 90,
    isEnabled: true,
    category: 'Heavy Lifting',
    description: 'Carton loading/unloading, tempo escorting & staircase carrying without lift',
  },
  {
    id: 'skilled-help',
    nameEn: 'Skilled Help',
    nameHi: 'कुशल सहायक',
    baseRate: 3.0,
    minDurationMins: 30,
    minAmount: 90,
    isEnabled: true,
    category: 'Semi-Skilled',
    description: 'Tech setup, smart TV / Wi-Fi, flatpack furniture assembly & wardrobe neatening',
  },
  {
    id: 'event-party-help',
    nameEn: 'Event & Party Help',
    nameHi: 'कार्यक्रम व पार्टी सहायता',
    baseRate: 3.0,
    minDurationMins: 30,
    minAmount: 90,
    isEnabled: true,
    category: 'Events & Hospitality',
    description: 'Decoration setup, guest coordination, catering support & seating organization',
  },
  {
    id: 'queue-waiter',
    nameEn: 'Queue (Line) Waiter',
    nameHi: 'कतार (लाइन) में खड़े रहना',
    baseRate: 2.0,
    minDurationMins: 30,
    minAmount: 60,
    isEnabled: true,
    category: 'Queue Management',
    description: 'Hospital tokens, railway tatkal ticket counter, school forms & temple darshan line',
  },
];

export const INITIAL_GLOBAL_SETTINGS: GlobalPlatformSettings = {
  platformCommissionPct: 15,
  commissionLockThresholdAmount: 100,
  commissionLockThresholdOrders: 3,
  matchingRadiusSteps: '3km, 5km, 7km',
  customerCancelPenalty: 20,
  autoAssignBufferMins: 5,
  emergencyEscalationDelaySecs: 45,
};

export const INITIAL_PENDING_COMMISSIONS: PendingCommissionItem[] = [
  {
    id: 'comm-1',
    partnerId: 'PTR-1003',
    partnerName: 'Rahul Sharma',
    partnerPhone: '+91 98765 43210',
    amountDue: 85,
    ordersCount: 2,
    status: 'PENDING',
    upiId: 'rahul.sharma@okaxis',
    dueDate: '21 Sep 2026',
  },
  {
    id: 'comm-2',
    partnerId: 'PTR-1006',
    partnerName: 'Dinesh Yadav',
    partnerPhone: '+91 99112 23344',
    amountDue: 145,
    ordersCount: 4,
    status: 'THRESHOLD_LOCKED',
    upiId: 'dinesh.yadav@ybl',
    dueDate: 'Overdue (Auto Locked)',
  },
  {
    id: 'comm-3',
    partnerId: 'PTR-1005',
    partnerName: 'Sunita Devi',
    partnerPhone: '+91 97654 32109',
    amountDue: 60,
    ordersCount: 1,
    status: 'PENDING',
    upiId: 'sunita.devi@paytm',
    dueDate: '22 Sep 2026',
  },
  {
    id: 'comm-4',
    partnerId: 'PTR-1004',
    partnerName: 'Vikram Patel',
    partnerPhone: '+91 98112 34567',
    amountDue: 0,
    ordersCount: 0,
    status: 'SETTLED',
    upiId: 'vikram.patel@icici',
    dueDate: 'Settled Today',
  },
];

export const INITIAL_CUSTOMER_PENALTIES: CustomerPenaltyItem[] = [
  {
    id: 'pen-1',
    customerId: 'CUST-802',
    customerName: 'Amit Verma',
    customerPhone: '+91 91234 56780',
    owedPenalty: 20,
    reason: 'Cancelled order #8812 post partner arrival (after 5 mins)',
    nextOrderBlockStatus: 'BLOCKED',
    cancelledOrderId: '#8812',
    date: '20 Sep 2026, 09:40 AM',
  },
  {
    id: 'pen-2',
    customerId: 'CUST-819',
    customerName: 'Suresh Chandra',
    customerPhone: '+91 99345 67890',
    owedPenalty: 20,
    reason: 'No-show after 10-min wait timer expired on Order #8890',
    nextOrderBlockStatus: 'WARNING',
    cancelledOrderId: '#8890',
    date: '20 Sep 2026, 11:05 AM',
  },
  {
    id: 'pen-3',
    customerId: 'CUST-750',
    customerName: 'Megha Singhal',
    customerPhone: '+91 94150 12345',
    owedPenalty: 40,
    reason: 'Repeat cancellation post dispatch (Order #8710 & #8792)',
    nextOrderBlockStatus: 'BLOCKED',
    cancelledOrderId: '#8792',
    date: '19 Sep 2026, 06:12 PM',
  },
];

export const INITIAL_AUDIT_LOGS: FraudAuditLog[] = [
  {
    id: 'log-01',
    timestamp: '2026-09-20 11:04:12',
    entityId: 'PTR-1006',
    entityName: 'Dinesh Yadav',
    entityType: 'Partner',
    event: 'Partner locked for 12h (3 cancellations in 24h).',
    actionTaken: 'Auto-Lock Applied by Safety Engine',
    severity: 'CRITICAL',
    isOverridden: false,
  },
  {
    id: 'log-02',
    timestamp: '2026-09-20 10:48:55',
    entityId: 'PTR-1008',
    entityName: 'Suraj Bhan',
    entityType: 'Partner',
    event: 'GPS Anomaly detected: Instant teleport 14km in 40 seconds (Mock location suspect).',
    actionTaken: 'Dispatch Restricted. Sensor Audit Telemetry Captured.',
    severity: 'CRITICAL',
    isOverridden: false,
  },
  {
    id: 'log-03',
    timestamp: '2026-09-20 10:22:10',
    entityId: 'CUST-802',
    entityName: 'Amit Verma',
    entityType: 'Customer',
    event: 'Post-arrival cancellation logged. ₹20 penalty billed to ledger.',
    actionTaken: 'Next Order Dispatch Gate Locked until fee settled.',
    severity: 'WARNING',
    isOverridden: false,
  },
  {
    id: 'log-04',
    timestamp: '2026-09-20 09:15:30',
    entityId: 'SYS-GLOBAL',
    entityName: 'Dispatch Engine',
    entityType: 'System',
    event: 'Surge auto-expansion radius triggered from 3km to 5km for Gomti Nagar hub.',
    actionTaken: 'Expanded Radius to 5km for 4 pending Hospital Assistance requests.',
    severity: 'INFO',
    isOverridden: false,
  },
  {
    id: 'log-05',
    timestamp: '2026-09-19 18:30:00',
    entityId: 'PTR-1002',
    entityName: 'Pooja Singh',
    entityType: 'Partner',
    event: 'Fresh KYC submission: Aadhaar & PAN uploaded with selfie.',
    actionTaken: 'Queued for Manual Admin Service Assignment & Approval.',
    severity: 'INFO',
    isOverridden: false,
  },
];
